# RandomValueConfig & AnotherRandomValueConfig
random-value:
  secret: ${random.value}
  number: ${random.int}
  big-number: ${random.long(1,9999999999)}
  uuid: ${random.uuid}
  less-ten: ${random.int(10)}
  range: ${random.int[1,100]}

# AppInfoConfig
app-info:
  server: 127.0.0.1
  port: 100098
  name: JavaWeb
  description: ${app.name} is a Spring Boot application

# StandardConfig
standard:
  username: standard
  password: z32M0vpgLQzmKCUk
  inet-address-list:
    - 226.9.155.25
    - 137.250.72.192
    - 112.158.137.142
    - 146.171.133.73
    - 26.229.232.254

# ConstructorBingingConfig
constructor:
  username: constructor
  password: EiWHROwMVigVCv8u
  inet-address-list:
    - 158.40.224.180
    - 239.222.129.209
    - 252.90.31.93
    - 21.14.132.91
    - 125.156.144.7

# MultiConstructorBingingConfig
multi-constructor:
  username: multiConstructor
  password: Igr226CiaDwXCs14
  inet-address-list:
    - 179.74.81.55
    - 206.34.196.205
    - 231.160.85.178
    - 163.85.5.251
    - 40.197.222.155

# YmlConf
yaml:
  string-list:
    - oee1YrIv
    - BI1xzzKm
    - Ue1fH1Qk
  string-object-map:
    Integer: 1
    Long: 999999999
    Boolean: true
    Character: a

  string-array:
    - oee1YrIv
    - BI1xzzKm
    - Ue1fH1Qk

# ServerProperties
web.server:
  application:
    name: InjectMapFromYAML
    url: http://injectmapfromyaml.dev
    description: How To Inject a map from a YAML File in Spring Boot
  config:
    ip-list:
      - 10.10.10.10
      - 10.10.10.11
      - 10.10.10.12
      - 10.10.10.13
    file-system:
      - /dev/root
      - /dev/md2
      - /dev/md4
  users:
    root:
      username: root
      password: Ti3Ka3x8T8y0cPrfuYIj
    guest:
      username: guest
      password: m8CW0LO3GGIsclO207DE

# AppSystemProperties
app.system:
  month-map:
    1: [ Jan. ]
    2: [ Feb. ]
    3: [ Mar. ]
    4: [ Apr. ]
    5: [ May ]
    6: [ Jun. ]
    7: [ Jul. ]
    8: [ Aug. ]
    9: [ Sep. ]
    10: [ Oct. ]
    11: [ Nov. ]
    12: [ Dec. ]
  system-users:
    root: { "username": "mate-master","password": "gLObQK0kZZVMVsOCIhaK" }
    guest: { "username": "jackson","password": "gWf6Tz5WiOgsUqSUFxam" }
