# LoginUser
login.user:
  uuid: eb0b23fe-4264-4f2f-9805-0b71bfe64131
  roles:
    - super tube
    - admin
    - guest
    - auditor
    - clerk

#  MacStudio 关于本机
mac-studio:
  overview:
    os-info: macos monterey 12.6
    model: Mac Studio (2022)
    silicon: Apple M1 Max
    memory: 64
    sequence-number: VQJ45YYX007
  display: DELL S2421HSX显示器
  store-space: 1TB
  supports: [ 硬件保障,聊天与电话支持,有限保修 ]
  resources:
    mac:
      - 技术规格
      - 硬件支持
      - 监管认证
      - 重要信息
    macos:
      - macos帮助手册
      - 使用手册
      - macos支持

