list:
  - 10010
  - 10020
  - 10030

array: [ 1,2,3,4,5,6,7,8,9,0 ]

map:
  key0: value0
  key1: value1
  key2: value2
  key3: value3

configurable-yaml:
  username: matemaster
  age: 24
  ports: [ 8080,8090,9000,9200,9100,9300 ]
  servers:
    - 10.37.129.100
    - 10.37.129.101
    - 10.37.129.102
    - 10.37.129.103
  log-map:
    off: 关闭
    fatal: 致命
    error: 错误
    warn: 警告
    info: 信息
    debug: 调试
    trace: 跟踪
  http-code:
    '[200系列]':
      - 200
      - 201
      - 202
      - 203
      - 204
    '[300系列]':
      - 300
      - 301
      - 302
    '[400系列]':
      - 400
      - 403
      - 404
    '[500系列]':
      - 500
      - 502
  computer-year: 1970-01-01
  enable: on
  com: Oracle

driver-class: &Driver com.mysql.cj.Driver

driver: *Driver
