spring:
  profiles:
    active: dev

springdoc:
  api-docs:
    path: openAPI/v3
    enabled: on
    version: openapi_3_0
  packages-to-scan:
    - cs.matemaster.controller
    - cs.matemaster.domain
    - cs.matemaster.model